name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run install
        run: npm ci

      - name: Run typecheck
        run: npm exec -w battlesnake -w battlesnake-plugin-ngrok -c 'tsc --noEmit'
